### ISSUE TITLE
New Github-hosted package causes the listing creation job to fail with a useless error message

### ISSUE THREAD

**Issue by FairlySadPanda** [vrchat-community/template-package-listing#10]
**Summary**
Even when following the VRC-recommended package setup steps, using the provided in-Editor tool, our trivial VRCBCE2 project crashes the list creation job.

**Steps to reproduce**
1. Create a new VCC repo
2. Add a newly created Github-hosted package to the githubRepos array in the repo's source.json file. The package must not have a release on Github.
3. Commit the change and wait for the Github Action to complete.

**Expected outcome**
The Action concludes without error.

**Actual outcome**
The list building job will throw the following exception:

```  
System.ArgumentNullException: Value cannot be null. (Parameter 'collection')
     at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
     at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
     at VRC.PackageManagement.Automation.Build.<get_BuildRepoListing>b__24_1() in /home/runner/work/vcc-repo/vcc-repo/ci/PackageBuilder/Build.cs:line 166
     at Nuke.Common.Execution.TargetDefinition.<>c__DisplayClass77_0.<Executes>b__0() in /_/source/Nuke.Common/Execution/TargetDefinition.cs:line 71
     at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x) in /_/source/Nuke.Common/Execution/BuildExecutor.cs:line 112
     at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action) in /_/source/Nuke.Common/Utilities/Collections/Enumerable.ForEach.cs:line 17
     at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode) in /_/source/Nuke.Common/Execution/BuildExecutor.cs:line 112
```

**Additional information**
This will not occur if the repo has had a release.

**Comment by FairlySadPanda** [comment]
Other minor complaint: the action doesn't support the `act` testing tool, reporting `ci/build.cmd: line 3: /mnt/f/VRChat: No such file or directory` during the building job.

**Comment by FairlySadPanda** [comment]
I've updated this ticket with the bug format I usually follow and a clearer bug to report. This is adjacent to issue #11.
